apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: yasmeen
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      spec:
      containers:
      - name: dockerdep-10-app
        image: dockerregister12.azurecr.io/dotnet-1-web
        ports: 
        - containerPort: 5000
        imagepullsecrets:
        - name: aks12