apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yasmeen
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
       —namespace: yasmeen
          image: dotnet-1-web:latest

          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
              ports: 
             —containerPort: 80