apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: dotnetdemo
spec:
  selector:
    matchLabels:
      app: dotnetdemo
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: yasmeen
        image: dotnet-1-web:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
