apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: dockerdep-10-app
        image: dockerregister12.azurecr.io/dotnet-1-web
        ports: 80
        - containerPort: 5000
        imagepullsecrets:
        - name: aks12