apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: yasmeen
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: default
      tolerations:    # Add the tolerations section for Tolerations
      - key: user
        operator: Equal
        value: yasmeen
        effect: NoSchedule
      containers:
      - name: dockerdep-10-app
      image: probe1.azurecr.io/dotnet:1.0
      ports:
       - containerPort: 80