apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-1-web
  namespace: yasu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-1-web
  template:
    metadata:
      labels:
        app: dotnet-1-web
    spec:
      containers:
      - name: dotnet-1-web
        image: yasmeenmaligeli/dotnet-1-web
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: CONFIG_KEY
          valueFrom:
            configMapKeyRef:
              name: -1-wedotnetb-configmap
              key: ENV_VARIABLE_1