apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: yasmeen
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
      image: probe1.azurecr.io/dotnet-1-web  
      ports:
       - containerPort: 80
      resources:
        requests:
          cpu: "100m" 
        limits:
         cpu: "300m" 
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: CONFIG_KEY
          valueFrom:
            configMapKeyRef:
              name: myapp-configmap
              key: ENV_VARIABLE_1