apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myapp
  namespace: yasmeen
subjects:
  - kind: ServiceAccount
    name: myapp
    namespace: yasmeen
roleRef:
  kind: Role
  name: myapp
  apiGroup: rbac.authorization.k8s.io